SUBROUTINE VIEWCONFIG(FILENAME)

    USE COMMONS, ONLY: VIEWUNIT, HST, YUKT, GLJT, KIHARAT, KFT, PGLJT, CPPT, ETPT, DMBLGLJT, KFRECT, HDMBLT, HTPRT
    USE COMMONS, ONLY: BHST, BGLJT, NMTCCT, OBLATESPHYT, TRIANGLET, POLYCHAINT

    IMPLICIT NONE

    CHARACTER (LEN=*) :: FILENAME

    OPEN(VIEWUNIT,FILE=FILENAME,STATUS='UNKNOWN',ACCESS='APPEND')

    IF(HST .OR. YUKT .OR. GLJT .OR. NMTCCT) THEN
        CALL VIEW_GLJ()
    ELSEIF(KIHARAT) THEN
        CALL VIEW_KIHARA()
    ELSEIF(KFT) THEN
        CALL VIEW_KF()
    ELSEIF(PGLJT) THEN
        CALL VIEW_PGLJ()
    ELSEIF(CPPT) THEN
        CALL VIEW_CPP()
    ELSEIF(ETPT .OR. HTPRT) THEN
        CALL VIEW_ETP()
    ELSEIF(DMBLGLJT) THEN
        CALL VIEW_DMBL_GLJ()
    ELSEIF(KFRECT) THEN
        CALL VIEW_KF_REC()
    ELSEIF(HDMBLT) THEN
        CALL VIEW_HDMBL()
    ELSEIF (BHST .OR. BGLJT) THEN
        CALL VIEW_BINARY_SPHERES()
    ELSEIF(OBLATESPHYT) THEN
        CALL VIEW_OBLATE_SPHEROCYLINDER()
    ELSEIF(TRIANGLET) THEN
        CALL VIEW_TRIANGLE()
    ELSEIF(POLYCHAINT) THEN
        CALL VIEW_GLJ()
    ENDIF

    CLOSE(UNIT=VIEWUNIT)

END SUBROUTINE VIEWCONFIG
